version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: eschool
      MYSQL_USER: eschool
      MYSQL_PASSWORD: 5rav_Pe5
      MYSQL_ROOT_PASSWORD: 5rav_Pe5